/* SPDX-License-Identifier: GPL-2.0 */
#ifndef UAPI_GOLDFISH_ADDRESS_SPACE_H
#define UAPI_GOLDFISH_ADDRESS_SPACE_H

#include <linux/types.h>

#define GOLDFISH_ADDRESS_SPACE_IOCTL_MAGIC		'A'
#define GOLDFISH_ADDRESS_SPACE_IOCTL_OP(OP, T)		_IOWR(GOLDFISH_ADDRESS_SPACE_IOCTL_MAGIC, OP, T)
#define GOLDFISH_ADDRESS_SPACE_IOCTL_ALLOCATE_BLOCK	GOLDFISH_ADDRESS_SPACE_IOCTL_OP(0, __u64)
#define GOLDFISH_ADDRESS_SPACE_IOCTL_DEALLOCATE_BLOCK	GOLDFISH_ADDRESS_SPACE_IOCTL_OP(1, __u64)

#endif /* UAPI_GOLDFISH_ADDRESS_SPACE_H */
